apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-12-29T17:59:49Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:containers:
          k:{"name":"cloud-sql-proxy"}:
            .: {}
            f:command: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
          k:{"name":"postgres"}:
            .: {}
            f:command: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
    manager: OpenAPI-Generator
    operation: Update
    time: "2021-12-29T17:59:48Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.4.8.156"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2021-12-29T17:59:53Z"
  name: migrate-wikitest-to-wikitest
  namespace: devops-psql
  resourceVersion: "37072739"
  uid: 5c3a7106-cf61-4dcb-b001-8140e6c64341
spec:
  containers:
  - command:
    - bash
    - -c
    - while :;do :; sleep 3000; done
    image: us-docker.pkg.dev/hits-devops-containerregi-4cb7/the-red-keep/postgres:13
    imagePullPolicy: IfNotPresent
    name: postgres
    resources:
      limits:
        cpu: "1"
        memory: 256Mi
      requests:
        cpu: "1"
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-z6bsw
      readOnly: true
  - command:
    - /cloud_sql_proxy
    - -instances=hits-devops-conf-test-4485:us-central1:confluence-test-psql-b6544d9c=tcp:5432,hits-devops-atlassian-std:us-central1:confluence-psql-4da1e467=tcp:5433
    image: us-docker.pkg.dev/hits-devops-containerregi-4cb7/the-red-keep/cloudsql-docker/gce-proxy:1.27.1
    imagePullPolicy: IfNotPresent
    name: cloud-sql-proxy
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-z6bsw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-prod-atlassian-prod-atlassian-nod-b534e945-blc6
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: devops-psql-sa
  serviceAccountName: devops-psql-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-z6bsw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-12-29T17:59:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-12-29T17:59:53Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-12-29T17:59:53Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-12-29T17:59:51Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://3b925232300dddbea63661caebc4992a540181b0cb855b90b5fb89fadcf1e805
    image: us-docker.pkg.dev/hits-devops-containerregi-4cb7/the-red-keep/cloudsql-docker/gce-proxy:1.27.1
    imageID: us-docker.pkg.dev/hits-devops-containerregi-4cb7/the-red-keep/cloudsql-docker/gce-proxy@sha256:a08c4520f3214695a5eb8e57ea76de6db7d669fbb1f73177d01c36c811e6e351
    lastState: {}
    name: cloud-sql-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-12-29T17:59:52Z"
  - containerID: containerd://ee2581a13e49595ad3ef44ce479902bc82bf11d765855fece965bf516f3870cd
    image: us-docker.pkg.dev/hits-devops-containerregi-4cb7/the-red-keep/postgres:13
    imageID: us-docker.pkg.dev/hits-devops-containerregi-4cb7/the-red-keep/postgres@sha256:4bca01db9119d6003c03e55843ad15c54ab5c3c1b4a374e5550ceed18b2808be
    lastState: {}
    name: postgres
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-12-29T17:59:52Z"
  hostIP: 10.4.0.11
  phase: Running
  podIP: 10.4.8.156
  podIPs:
  - ip: 10.4.8.156
  qosClass: Guaranteed
  startTime: "2021-12-29T17:59:51Z"

